### ISSUE TITLE
Run it on windows

### ISSUE THREAD

**Issue by MichielKE** [panodata/grafana-pandas-datasource#9]
Hi, I am trying to run this package from source on my windows machine. I followed the documentation [here](https://pypi.org/project/grafana-pandas-datasource/) and wrote kind of a `ReadMe`. 

I have got these steps...

```
# Run and example Pandas DataFrame with Grafana
1. Clone this repo from source
2. Cd into the folder
3. Create virtual environment by `python -m venv venv`
4. Activate the environment. Cd into `venv/Scripts` run `activate`
6. `pip install pandas grafana_pandas_datasource`
7. Install docker desktop
8. run container 
`docker run --rm -it --publish=3000:3000 --name grafana --env="GF_INSTALL_PLUGINS=grafana-simple-json-datasource" --env="GF_SECURITY_ADMIN_PASSWORD=<mypassword>" grafana/grafana-oss:7.3.6` 
or
`docker run --rm -it -d --publish=3000:3000 --name grafana --env="GF_INSTALL_PLUGINS=grafana-simple-json-datasource" --env="GF_SECURITY_ADMIN_PASSWORD=<mypassword>" grafana/grafana-oss:7.3.6`
9. go to `localhost:3000` in browser and setup a SimpleJson Datasource (see figure below)
10. Run the python sine-wave demo. Cd into `examples/sinewave-midnights` and run `python demo.py` 
11. What should be next?

```
What should I do next? How to get the dashboard and read the data? 

![image](https://user-images.githubusercontent.com/97875636/150339600-3db0f2d1-7421-40ad-8843-c501649db24a.png)

My localhost:3003 shows this:
![image](https://user-images.githubusercontent.com/97875636/150339708-17e753ba-4962-433e-82ef-d3e8d248a84a.png)

**Comment by amotl** [comment]
Dear @MichielKE,

thank you for writing in.

> What should I do next? How to get the dashboard and read the data?

You can follow the instructions at [1] in order to install appropriate datasource- and dashboard-entities which should get you started, at least this is the idea. Please let me know if anything goes wrong.

For invoking the commands verbatim, you will need to install the [HTTPie] program. You can well install it into the virtualenv you have created by invoking `pip install httpie`. I don't know how to translate the incantations into corresponding PowerShell commands, so maybe you could use `bash`, eventually from within WSL?

Let me know if that makes any sense to you. Otherwise we can try to find a different approach to make things work for you.

With kind regards,
Andreas.

P.S.: Also, I would like to reference the corresponding queries submitted to the backend daemon which is serving the dataframe, see [2,3]. Maybe this can also help you to figure out how things work.

[1] https://github.com/panodata/grafana-pandas-datasource/tree/main/examples/sinewave-midnights#configure-grafana
[2] https://github.com/panodata/grafana-pandas-datasource/blob/0.1.2/examples/sinewave-midnights/dashboard.json#L87
[3] https://github.com/panodata/grafana-pandas-datasource/blob/0.1.2/examples/sinewave-midnights/dashboard.json#L24

[HTTPie]: https://httpie.io/

**Comment by MichielKE** [comment]
Dear @amotl, thanks you for the fast response! I will check it out tomorrow and let you know how it goes.

**Comment by amotl** [comment]
Dear @MichielKE,

the documentation at [^1] and [^2] has been significantly improved. Maybe this helps. Please let us know about the outcome for you.

Please also note:
> When running Grafana in Docker, use `host.docker.internal` to address the Docker host [where the Flask HTTP service is running].

With kind regards,
Andreas.

[^1]: https://github.com/panodata/grafana-pandas-datasource/blob/main/README.rst
[^2]: https://github.com/panodata/grafana-pandas-datasource/blob/main/examples/sinewave-midnights/readme.rst

**Comment by MichielKE** [comment]
Hi Andreas, thanks for the update. Indeed I have been trying to get it to run on Windows, currently without success. Probably the fix it quite simple. Potentially I'll have a look at it with a colleague later this week, but last days my attention has shifted to use another data source as well (potentially Prometheus). I will keep you posted if I progress. 

I run Grafana in Docker:
`docker run --rm -it -d --publish=3000:3000 --name grafana -v grafana-storage:/var/lib/grafana --env="GF_INSTALL_PLUGINS=grafana-simple-json-datasource" --env="GF_SECURITY_ADMIN_PASSWORD=MYPASSWORD" grafana/grafana-oss:7.3.6` 
And the package from source by:
`python .\examples\sinewave-midnights\demo.py`

I configured the http to the `http://host.docker.internal:3003`, but when testing I get the following.  I stop here for now.

![image](https://user-images.githubusercontent.com/97875636/150957556-98fe5053-a191-4290-b86b-f4eb53db289b.png)

**Comment by amotl** [comment]
Hi again,

while I added screenshots to the documentation just recently [^1], I never actually pressed the "Save & Test" button. Hitting it, quickly reveals the problem:

![image](https://user-images.githubusercontent.com/453543/152436037-cd84bd32-e63e-4215-be2d-33bde53b1275.png)

That is probably the same thing @byteptr reported at #7 and https://github.com/grafana/simple-json-datasource/issues/167. 

~~It is because the [Simple JSON Datasource](https://grafana.com/grafana/plugins/grafana-simple-json-datasource/) forwards the "test datasource" request to `http://localhost:3000/api/datasources/proxy/1/` to `http://localhost:3003/`, which responds with `text/html`, which Grafana obviously doesn't like.~~ [^2]

This will clearly need a fix.

With kind regards,
Andreas.

[^1]: https://github.com/panodata/grafana-pandas-datasource/blob/main/examples/sinewave-midnights/readme.rst#gui
[^2]: Forget about this statement, see next comment instead.

**Comment by amotl** [comment]
I have been able to reproduce the problem.

### Observations

While regular GET and POST requests to the "test datasource" endpoint succeeds
```
$ http GET localhost:3003
$ http POST localhost:3003
HTTP/1.0 200 OK
```

a GET request made by the Simple JSON Datasource fails. The reason is that it sends a GET request with a HTTP header `Content-Type: application/json`, where Flask responds with "400 Bad Request" like
```
$ echo "" | http localhost:3003 Content-Type:application/json
HTTP/1.0 400 BAD REQUEST

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>Failed to decode JSON object: Expecting value: line 1 column 1 (char 0)</p>
```

That might be natural, because it is actually an empty GET request, without any content at all. On the other hand, sending a non-empty request body using a POST request succeeds:
```
$ echo "null" | http localhost:3003 Content-Type:application/json
HTTP/1.0 200 OK
```

### Evaluation

While it is not forbidden to send request bodies with `Content-Type` headers in GET requests, at least it is not a common case. However, Flask tries to decode an empty request body from JSON, where it croaks. It would be sweet if it would assume `null` instead. On the other hand, if the Simple JSON Datasource would not send the `Content-Type` header when there is no actual content, Flask would not croak.

**Comment by amotl** [comment]
Hi again,

#10 will resolve the problem you have been observing, thank you again for your report! Please let us know if you are observing any other issues. We will also be happy to hear back if it works for you now.

With kind regards,
Andreas.

**Comment by amotl** [comment]
Hi once more,

following up on your initial post, we improved the installation instructions for Windows with 410be9c6aac1af. Let us know if this works for you.

With kind regards,
Andreas.

**Comment by amotl** [comment]
Dear @MichielKE,

`grafana-pandas-datasource-0.3.0` has been released and includes this bugfix. Please let us know if you feel we addressed all your issues well, or what to improve otherwise.

With kind regards,
Andreas.

**Comment by MichielKE** [comment]
Thanks Andreas, once I get the chance to have a look at it I will let you know. Best, Michiel
